// <auto-generated />
using System;
using DailyTasks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyTasks.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714085107_AddMultipleAssignees")]
    partial class AddMultipleAssignees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DailyTasks.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#3B82F6",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#A855F7",
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#10B981",
                            Name = "Errands"
                        });
                });

            modelBuilder.Entity("DailyTasks.Models.InterruptionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinutesLost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Interruptions");
                });

            modelBuilder.Entity("DailyTasks.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PairedPhaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerTaskId");

                    b.HasIndex("PairedPhaseId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("DailyTasks.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BigThreeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextResumeNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedHours")
                        .HasColumnType("REAL");

                    b.Property<string>("GitLink")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitRepoPath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IterationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IterationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNudgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Methodology")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostponedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<int?>("SprintLengthDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Todo");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhyReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WipLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpPractices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("PhaseId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DailyTasks.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialsColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScrumRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerProjectId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("TaskItemTeamMember", b =>
                {
                    b.Property<int>("AssigneesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssigneesId", "TaskItemId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskAssignees", (string)null);
                });

            modelBuilder.Entity("DailyTasks.Models.InterruptionEvent", b =>
                {
                    b.HasOne("DailyTasks.Models.TaskItem", "TaskItem")
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DailyTasks.Models.Phase", b =>
                {
                    b.HasOne("DailyTasks.Models.TaskItem", "OwnerTask")
                        .WithMany("Phases")
                        .HasForeignKey("OwnerTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyTasks.Models.Phase", "PairedPhase")
                        .WithMany()
                        .HasForeignKey("PairedPhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerTask");

                    b.Navigation("PairedPhase");
                });

            modelBuilder.Entity("DailyTasks.Models.TaskItem", b =>
                {
                    b.HasOne("DailyTasks.Models.TeamMember", "AssignedTo")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DailyTasks.Models.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DailyTasks.Models.TaskItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DailyTasks.Models.Phase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("DailyTasks.Models.TeamMember", b =>
                {
                    b.HasOne("DailyTasks.Models.TaskItem", "OwnerProject")
                        .WithMany("ProjectTeam")
                        .HasForeignKey("OwnerProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("OwnerProject");
                });

            modelBuilder.Entity("TaskItemTeamMember", b =>
                {
                    b.HasOne("DailyTasks.Models.TeamMember", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DailyTasks.Models.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DailyTasks.Models.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DailyTasks.Models.Phase", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DailyTasks.Models.TaskItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Phases");

                    b.Navigation("ProjectTeam");
                });

            modelBuilder.Entity("DailyTasks.Models.TeamMember", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
